[package]
name = "pubcrypt"
version = "0.1.0"
authors = ["jk977"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
math = { path = "math" }
rand = "~0.8.3"
clap = "~2.33.3"

[workspace]
members = ["math"]
